export const IMS_SCHEMA_REQUIRED_TABLES = [
  'ims_contacts',
  'ims_locations',
  'pos_chat_messages',
  'pos_chat_attachments',
  'ims_settings',
  'ims_cs_settings',
  'ims_cs_threads',
  'ims_cs_messages',
  'ims_cs_drafts',
  'ims_cs_draft_revisions',
  'ims_cs_processing_runs',
  'ims_cs_events',
  'ims_cs_learning_evidence',
  'ims_cs_learning_candidates',
  'ims_cs_knowledge_documents',
  'ims_cs_knowledge_versions',
  'ims_products',
  'ims_product_variants',
  'ims_product_images',
  'ims_website_content_attempts',
  'ims_stock',
  'ims_purchase_orders',
  'ims_po_landed_costs',
  'ims_purchase_order_items',
  'ims_sales_orders',
  'ims_sales_order_items',
  'ims_so_fulfilment_operations',
  'ims_po_receive_operations',
  'ims_order_amendment_operations',
  'ims_order_amendment_lines',
  'ims_so_shortfall_resolutions',
  'ims_customer_credit_settlements',
  'ims_po_shortfall_resolutions',
  'ims_supplier_credit_settlements',
  'ims_po_backorder_lines',
  'ims_so_backorder_lines',
  'ims_backorder_merges',
  'ims_credit_notes',
  'ims_credit_note_items',
  'ims_supplier_credit_notes',
  'ims_supplier_credit_note_items',
  'ims_supplier_credit_note_files',
  'ims_stock_movements',
  'ims_stocktakes',
  'ims_stocktake_items',
  'ims_branch_transfers',
  'ims_branch_transfer_items',
  'pos_users',
  'pos_registers',
  'pos_register_sessions',
  'pos_sales',
  'pos_sale_items',
  'pos_payments',
  'pos_eod_reconciliations',
  'ims_sales_history',
  'ims_sales_cache',
  'ims_notifications',
  'gift_cards',
  'gift_card_transactions',
  'store_credit_transactions',
  'loyalty_accounts',
  'loyalty_transactions',
  'loyalty_rewards',
  'loyalty_redemptions',
] as const;

export const IMS_SCHEMA_REQUIRED_COLUMNS = {
  ims_locations: [
    'phone',
    'pos_pin',
    'manager_pin_hash',
    'cin7_branch_id',
    'has_pos',
    'has_wholesale',
    'has_online',
  ],
  ims_product_variants: [
    'cost_aud',
    'avg_cost',
    'price_rrp',
    'price_wholesale',
    'price_rrp_sale',
    'cost_foreign',
    'pack_size',
    'cin7_option_id',
    'bin',
    'zone',
    'volume',
    'shopify_inventory_item_id',
  ],
  ims_stock: ['zone', 'bin'],
  ims_purchase_orders: ['replacement_of_po_id'],
  ims_sales_orders: ['replacement_of_so_id'],
  ims_purchase_order_items: ['discount_pct'],
  ims_credit_note_items: ['source_so_item_id'],
  ims_supplier_credit_note_items: ['source_po_item_id'],
  store_credit_transactions: ['credit_note_id', 'idempotency_key'],
} as const;

export const IMS_SCHEMA_REQUIRED_INDEXES = {
  ims_purchase_orders: ['uq_po_replacement_source'],
  ims_sales_orders: ['uq_so_replacement_source'],
  ims_credit_notes: ['uq_business_cn'],
  ims_credit_note_items: ['idx_cn_source_so_item'],
  ims_supplier_credit_note_items: ['idx_scn_source_po_item'],
  store_credit_transactions: ['idx_sct_credit_note', 'uq_sct_idempotency'],
} as const;

export type ImsSchemaRequiredTable = keyof typeof IMS_SCHEMA_REQUIRED_COLUMNS;