export const IMS_SCHEMA_REQUIRED_TABLES = [
  'ims_contacts',
  'ims_crm_interactions',
  'ims_crm_tasks',
  'ims_crm_tags',
  'ims_crm_contact_tags',
  'ims_crm_segments',
  'ims_crm_pipeline_stages',
  'ims_crm_opportunities',
  'ims_crm_contact_merges',
  'ims_brands',
  'ims_bulk_product_presets',
  'ims_locations',
  'pos_chat_messages',
  'pos_chat_attachments',
  'ims_settings',
  'ims_cs_settings',
  'ims_cs_threads',
  'ims_cs_messages',
  'ims_cs_drafts',
  'ims_cs_draft_revisions',
  'ims_cs_processing_runs',
  'ims_cs_events',
  'ims_cs_learning_evidence',
  'ims_cs_learning_candidates',
  'ims_cs_knowledge_documents',
  'ims_cs_knowledge_versions',
  'ims_products',
  'ims_product_variants',
  'ims_product_images',
  'ims_shopify_sync_log',
  'ims_website_content_attempts',
  'ims_stock',
  'ims_stock_allocations',
  'ims_stock_allocation_operations',
  'ims_purchase_orders',
  'ims_po_landed_costs',
  'ims_purchase_order_items',
  'ims_purchase_order_payments',
  'ims_sales_orders',
  'ims_sales_order_items',
  'ims_sales_order_payments',
  'ims_so_fulfilment_operations',
  'ims_so_shipments',
  'ims_so_shipment_items',
  'ims_so_shipment_tracking',
  'ims_po_receive_operations',
  'ims_order_amendment_operations',
  'ims_inventory_document_operations',
  'ims_order_amendment_lines',
  'ims_so_shortfall_resolutions',
  'ims_customer_credit_settlements',
  'ims_po_shortfall_resolutions',
  'ims_supplier_credit_settlements',
  'ims_po_backorder_lines',
  'ims_so_backorder_lines',
  'ims_backorder_merges',
  'ims_credit_notes',
  'ims_credit_note_items',
  'ims_supplier_credit_notes',
  'ims_supplier_credit_note_items',
  'ims_supplier_credit_note_files',
  'ims_stock_movements',
  'ims_stocktakes',
  'ims_stocktake_items',
  'ims_branch_transfers',
  'ims_branch_transfer_items',
  'pos_users',
  'pos_registers',
  'pos_register_sessions',
  'pos_sales',
  'pos_training_sales',
  'pos_daybook_staff_identities',
  'pos_daybook_task_templates',
  'pos_daybook_task_instances',
  'pos_daybook_task_signoffs',
  'pos_daybook_communications',
  'pos_daybook_communication_targets',
  'pos_daybook_communication_reads',
  'pos_daybook_records',
  'pos_daybook_record_events',
  'pos_daybook_comments',
  'pos_daybook_references',
  'pos_daybook_product_guides',
  'pos_daybook_import_runs',
  'pos_daybook_content_events',
  'pos_sale_items',
  'pos_payments',
  'pos_petty_cash_transactions',
  'pos_eod_reconciliations',
  'ims_wholesale_companies',
  'ims_wholesale_company_locations',
  'ims_wholesale_company_members',
  'ims_wholesale_member_locations',
  'ims_wholesale_saved_lists',
  'ims_wholesale_saved_list_items',
  'ims_wholesale_favourites',
  'ims_wholesale_team_events',
  'wholesale_draft_orders',
  'wholesale_draft_order_items',
  'ims_sales_history',
  'ims_sales_cache',
  'ims_notifications',
  'ims_online_shop_products',
  'ims_online_shop_customers',
  'ims_online_shop_addresses',
  'ims_online_shop_shipping_rules',
  'ims_online_shop_pickup_locations',
  'ims_online_shop_checkouts',
  'ims_online_shop_fulfilment_groups',
  'ims_online_shop_checkout_items',
  'ims_online_shop_stock_reservations',
  'ims_online_shop_payment_attempts',
  'ims_online_shop_payment_events',
  'ims_online_shop_value_reservations',
  'ims_online_shop_refunds',
  'gift_cards',
  'gift_card_transactions',
  'store_credit_transactions',
  'loyalty_accounts',
  'loyalty_membership_events',
  'loyalty_transactions',
  'loyalty_rewards',
  'loyalty_redemptions',
] as const;

export const IMS_SCHEMA_REQUIRED_COLUMNS = {
  loyalty_redemptions: ['expires_at'],
  ims_brands: ['business_id', 'name', 'website_url', 'updated_at'],
  ims_bulk_product_presets: ['business_id', 'user_key', 'name', 'settings_json', 'last_used_at', 'created_at', 'updated_at'],
  pos_training_sales: ['business_id', 'local_id', 'location_id', 'items_json', 'payments_json', 'created_at'],
  pos_daybook_task_signoffs: ['business_id', 'staff_name', 'staff_initials', 'actor_user_id', 'actor_name', 'actor_tier', 'created_at'],
  pos_daybook_communication_reads: ['business_id', 'location_id', 'staff_name', 'staff_initials', 'actor_user_id', 'actor_name', 'read_at'],
  pos_daybook_comments: ['business_id', 'location_id', 'item_type', 'item_id', 'comment_text', 'staff_name', 'staff_initials', 'actor_user_id', 'actor_name', 'created_at'],
  pos_daybook_task_templates: ['created_by_id', 'created_by_staff_identity_id', 'created_by_staff_initials'],
  pos_daybook_communications: ['author_user_id', 'author_staff_identity_id', 'author_staff_initials', 'background_color'],
  pos_daybook_records: ['business_id', 'location_id', 'record_type', 'status', 'details_json', 'staff_name', 'staff_initials', 'actor_name', 'background_color'],
  pos_daybook_references: ['secret_label', 'secret_value_encrypted', 'background_color', 'author_user_id', 'author_staff_identity_id', 'author_staff_initials'],
  pos_daybook_product_guides: ['background_color', 'author_user_id', 'author_staff_identity_id', 'author_staff_initials'],
  pos_daybook_content_events: ['business_id', 'location_id', 'item_type', 'item_id', 'action', 'staff_identity_id', 'staff_name', 'staff_initials', 'actor_user_id', 'actor_name', 'actor_tier', 'created_at'],
  ims_locations: [
    'phone',
    'pos_pin',
    'manager_pin_hash',
    'cin7_branch_id',
    'has_pos',
    'has_wholesale',
    'has_online',
  ],
  ims_product_variants: [
    'cost_aud',
    'avg_cost',
    'price_rrp',
    'price_wholesale',
    'price_rrp_sale',
    'cost_foreign',
    'pack_size',
    'cin7_option_id',
    'bin',
    'zone',
    'volume',
    'shopify_inventory_item_id',
  ],
  ims_stock: ['zone', 'bin'],
  ims_wholesale_companies: ['business_id', 'primary_contact_id', 'company_name', 'status'],
  ims_wholesale_company_locations: ['business_id', 'company_id', 'location_name', 'is_primary', 'status'],
  ims_wholesale_company_members: ['business_id', 'company_id', 'location_id', 'contact_id', 'role', 'is_active'],
  ims_wholesale_member_locations: ['business_id', 'company_id', 'member_id', 'location_id'],
  ims_wholesale_saved_lists: ['business_id', 'company_id', 'created_by_member_id', 'name'],
  ims_wholesale_saved_list_items: ['business_id', 'list_id', 'variant_id', 'quantity'],
  ims_wholesale_favourites: ['business_id', 'company_id', 'member_id', 'variant_id'],
  ims_wholesale_team_events: ['business_id', 'company_id', 'actor_member_id', 'target_member_id', 'target_contact_id', 'action', 'details_json'],
  ims_stock_allocations: ['qty_allocated', 'qty_received_assigned', 'qty_fulfilled', 'promise_status', 'state', 'revision'],
  ims_stock_allocation_operations: ['operation_key', 'request_hash', 'action', 'state'],
  wholesale_draft_orders: ['wholesale_company_id', 'wholesale_location_id', 'wholesale_member_id', 'is_staff_preview_test', 'staff_preview_session_id', 'staff_preview_actor_user_id', 'staff_preview_actor_name'],
  wholesale_draft_order_items: ['is_indent', 'indent_qty'],
  ims_purchase_orders: ['replacement_of_po_id'],
  ims_sales_orders: ['replacement_of_so_id', 'wholesale_company_id', 'wholesale_location_id', 'wholesale_member_id', 'is_staff_preview_test', 'staff_preview_session_id', 'staff_preview_actor_user_id', 'staff_preview_actor_name', 'sales_channel', 'native_checkout_id'],
  ims_purchase_order_items: ['discount_pct'],
  ims_purchase_order_payments: [
    'business_id',
    'payment_method_id',
    'xero_post_intent',
    'xero_post_status',
    'xero_payment_id',
    'xero_post_error',
    'xero_posted_at',
  ],
  ims_sales_order_payments: [
    'business_id',
    'payment_method_id',
    'xero_post_intent',
    'xero_post_status',
    'xero_payment_id',
    'xero_post_error',
    'xero_posted_at',
  ],
  ims_credit_note_items: ['source_so_item_id'],
  ims_credit_notes: [
    'reversed_at',
    'reversal_reason',
    'reversed_by',
    'xero_correction_status',
    'xero_correction_reference',
    'xero_correction_error',
  ],
  ims_supplier_credit_notes: [
    'reversed_at',
    'reversal_reason',
    'reversed_by',
    'xero_correction_status',
    'xero_correction_reference',
    'xero_correction_error',
  ],
  ims_supplier_credit_note_items: ['source_po_item_id'],
  ims_stocktakes: [
    'reverted_at',
    'reversal_reason',
    'reversed_by',
    'xero_reversal_journal_id',
    'xero_reversal_synced_at',
    'xero_reversal_sync_status',
    'xero_reversal_error',
    'updated_at',
  ],
  ims_stocktake_items: ['soh_at_apply', 'applied_delta', 'unit_cost_at_apply'],
  store_credit_transactions: ['credit_note_id', 'idempotency_key'],
  ims_online_shop_refunds: ['credit_note_id', 'checkout_id', 'so_id', 'contact_id', 'provider_refund_id', 'stripe_cents', 'store_credit_cents', 'status', 'idempotency_key'],
} as const;

export const IMS_SCHEMA_REQUIRED_INDEXES = {
  ims_brands: ['uq_ims_brand_per_tenant', 'idx_ims_brand_business'],
  ims_bulk_product_presets: ['uq_bulk_product_preset_name', 'idx_bulk_product_preset_user'],
  pos_training_sales: ['uq_pos_training_local', 'idx_pos_training_location'],
  ims_crm_interactions: ['idx_crm_interaction_timeline'],
  ims_crm_tasks: ['idx_crm_task_contact', 'idx_crm_task_assignee'],
  ims_crm_tags: ['uq_crm_tag_name', 'idx_crm_tag_lookup'],
  ims_crm_contact_tags: ['uq_crm_contact_tag', 'idx_crm_contact_tag_lookup'],
  ims_inventory_document_operations: ['uq_inventory_document_operation', 'idx_inventory_document_history'],
  ims_purchase_orders: ['uq_po_replacement_source'],
  ims_sales_orders: ['uq_so_replacement_source', 'idx_so_wholesale_account', 'idx_so_staff_preview', 'idx_so_online_channel', 'uq_so_native_checkout'],
  wholesale_draft_orders: ['idx_wholesale_draft_account', 'idx_wholesale_draft_preview'],
  ims_credit_notes: ['uq_business_cn'],
  ims_credit_note_items: ['idx_cn_source_so_item'],
  ims_supplier_credit_note_items: ['idx_scn_source_po_item'],
  ims_wholesale_companies: ['uq_wholesale_company_contact', 'idx_wholesale_company_status'],
  ims_wholesale_company_locations: ['uq_wholesale_company_location', 'idx_wholesale_location_primary'],
  ims_wholesale_company_members: [
    'uq_wholesale_company_member',
    'idx_wholesale_member_contact',
    'idx_wholesale_member_location',
  ],
  store_credit_transactions: ['idx_sct_credit_note', 'uq_sct_idempotency'],
  ims_online_shop_refunds: ['uq_online_shop_refund_cn', 'uq_online_shop_refund_key', 'idx_online_shop_refund_checkout'],
} as const;

export type ImsSchemaRequiredTable = keyof typeof IMS_SCHEMA_REQUIRED_COLUMNS;