import { imsExecute, imsQuery } from '@/services/IMSMySQLService';
import { allocateXeroCreditNote } from '@/services/XeroSyncService';
import { reportRuntimeIssue } from '@/lib/runtimeIssues';

export async function allocateReservedCustomerCredit(businessId:string,soId:number):Promise<void>{
  const queried=await imsQuery<any>(`SELECT s.id,s.action_key,s.amount,cn.xero_credit_note_id,so.xero_invoice_id FROM ims_customer_credit_settlements s JOIN ims_so_shortfall_resolutions r ON r.id=s.resolution_id AND r.business_id=s.business_id JOIN ims_credit_notes cn ON cn.id=r.credit_note_id AND cn.business_id=s.business_id JOIN ims_sales_orders so ON so.id=s.target_so_id AND so.business_id=s.business_id WHERE s.business_id=? AND s.target_so_id=? AND s.action_type='reserve_for_order' AND s.status IN ('planned','failed')`,[businessId,soId]);
  const rows=Array.isArray(queried)?queried:[];
  for(const action of rows){if(!action.xero_credit_note_id||!action.xero_invoice_id)continue;const claimed=await imsExecute(`UPDATE ims_customer_credit_settlements SET status='running',safe_error=NULL WHERE id=? AND business_id=? AND status IN ('planned','failed')`,[action.id,businessId]);if(!claimed.affectedRows)continue;try{const allocationId=await allocateXeroCreditNote({businessId,creditNoteId:String(action.xero_credit_note_id),invoiceId:String(action.xero_invoice_id),amount:Number(action.amount),actionKey:String(action.action_key)});await imsExecute(`UPDATE ims_customer_credit_settlements SET status='succeeded',xero_id=?,target_xero_document_id=?,completed_at=NOW() WHERE id=?`,[allocationId,action.xero_invoice_id,action.id]);}catch(error:any){await imsExecute(`UPDATE ims_customer_credit_settlements SET status='failed',safe_error=? WHERE id=?`,[String(error?.message??error).slice(0,500),action.id]);await reportRuntimeIssue({businessId,source:'ims_sales_orders',operation:'allocate_reserved_credit',title:'Reserved customer credit allocation failed',error,reference:{type:'sales_order',id:String(soId)}});}}
}

export async function allocateReservedSupplierCredit(businessId:string,poId:number):Promise<void>{
  const queried=await imsQuery<any>(`SELECT s.id,s.action_key,s.amount,scn.xero_credit_note_id,po.xero_bill_id FROM ims_supplier_credit_settlements s JOIN ims_po_shortfall_resolutions r ON r.id=s.resolution_id AND r.business_id=s.business_id JOIN ims_supplier_credit_notes scn ON scn.id=r.supplier_credit_note_id AND scn.business_id=s.business_id JOIN ims_purchase_orders po ON po.id=s.target_po_id AND po.business_id=s.business_id WHERE s.business_id=? AND s.target_po_id=? AND s.action_type='reserve_for_order' AND s.status IN ('planned','failed')`,[businessId,poId]);
  const rows=Array.isArray(queried)?queried:[];
  for(const action of rows){if(!action.xero_credit_note_id||!action.xero_bill_id)continue;const claimed=await imsExecute(`UPDATE ims_supplier_credit_settlements SET status='running',safe_error=NULL WHERE id=? AND business_id=? AND status IN ('planned','failed')`,[action.id,businessId]);if(!claimed.affectedRows)continue;try{const allocationId=await allocateXeroCreditNote({businessId,creditNoteId:String(action.xero_credit_note_id),invoiceId:String(action.xero_bill_id),amount:Number(action.amount),actionKey:String(action.action_key)});await imsExecute(`UPDATE ims_supplier_credit_settlements SET status='succeeded',xero_id=?,target_xero_document_id=?,completed_at=NOW() WHERE id=?`,[allocationId,action.xero_bill_id,action.id]);}catch(error:any){await imsExecute(`UPDATE ims_supplier_credit_settlements SET status='failed',safe_error=? WHERE id=?`,[String(error?.message??error).slice(0,500),action.id]);await reportRuntimeIssue({businessId,source:'ims_purchase_orders',operation:'allocate_reserved_credit',title:'Reserved supplier credit allocation failed',error,reference:{type:'purchase_order',id:String(poId)}});}}
}
