import { NextResponse } from 'next/server';
import { getImsSession } from '@/lib/auth/imsSession';
import { previewSupplierResolution,resolveSupplierOutstanding,type SupplierSettlement } from '@/lib/ims/orderResolution/supplierResolution';
import type { OrderResolutionOutcome } from '@/lib/ims/orderResolution/domain';
import { ImsPORepo, ImsSupplierCNRepo } from '@/lib/ims/ImsRepository';
import { imsExecute } from '@/services/IMSMySQLService';
import { approveCreditNote,refundXeroCreditNote,syncSupplierCNAsCreditNote,updateXeroDraftBill } from '@/services/XeroSyncService';
import { reportRuntimeIssue } from '@/lib/runtimeIssues';
const OUTCOMES=new Set<OrderResolutionOutcome>(['leave_partial','cancel_remainder','create_backorder']);const SETTLEMENTS=new Set<SupplierSettlement>(['none','supplier_refund','leave_unapplied','reserve_for_new_po']);
export async function POST(req:Request,{params}:{params:{id:string}}){const session=await getImsSession();if(!session)return NextResponse.json({error:'Not authenticated'},{status:401});const businessId=session.businessId as string;const poId=Number(params.id);if(!Number.isInteger(poId)||poId<=0)return NextResponse.json({error:'Invalid purchase order ID.'},{status:400});try{const body=await req.json();const outcome=String(body.outcome??'') as OrderResolutionOutcome;const settlement=String(body.settlement??'none') as SupplierSettlement;const operationKey=String(body.operationKey??'').trim();if(!OUTCOMES.has(outcome)||!SETTLEMENTS.has(settlement)||!operationKey)return NextResponse.json({error:'A valid outcome, settlement, and operation key are required.'},{status:400});const preview=await previewSupplierResolution(businessId,poId,outcome);if(preview.accounting.kind==='blocked')return NextResponse.json({error:preview.accounting.message},{status:409});if(!preview.settlements.includes(settlement))return NextResponse.json({error:'That settlement is not valid for this resolution.'},{status:400});if(settlement==='supplier_refund'&&!String(body.accountCode??'').trim())return NextResponse.json({error:'Choose a Xero bank account for the supplier refund.'},{status:400});const result:any=await resolveSupplierOutstanding({businessId,poId,operationKey,outcome,settlement,supplierCreditRef:String(body.supplierCreditRef??'').trim()||undefined,evidenceNote:String(body.evidenceNote??'').trim()||undefined,preview,createdBy:String(session.userId??'')});if(outcome==='leave_partial')return NextResponse.json({success:true,data:result});
if(preview.accounting.kind==='resize_xero_document'){const resized:any=await ImsPORepo.get(poId,businessId);if(!resized||!resized.xero_bill_id||!await updateXeroDraftBill(businessId,resized,resized.xero_bill_id))throw new Error('Xero did not accept the resized supplier bill. The local resolution is pending reconciliation.');await imsExecute(`UPDATE ims_po_shortfall_resolutions SET state='complete',completed_at=NOW() WHERE id=?`,[result.resolutionId]);result.state='complete';}
else if(preview.accounting.kind==='create_credit_note'&&result.supplierCreditNoteId){const scn:any=await ImsSupplierCNRepo.get(result.supplierCreditNoteId,businessId);if(!scn)throw new Error('The supplier shortfall credit note could not be reloaded.');const xeroCreditNoteId=await syncSupplierCNAsCreditNote(businessId,scn);if(!xeroCreditNoteId)throw new Error('Xero did not create the supplier shortfall credit note.');if(!await approveCreditNote(businessId,xeroCreditNoteId,result.supplierCreditNoteId,'scn_credit_note'))throw new Error('Xero did not Authorise the supplier credit note.');if(settlement==='supplier_refund'){const paymentId=await refundXeroCreditNote({businessId,creditNoteId:xeroCreditNoteId,amount:preview.totals.totalAmount,accountCode:String(body.accountCode).trim(),date:new Date().toISOString().slice(0,10),reference:`Supplier shortfall ${scn.scn_number}`,actionKey:`${operationKey}:supplier_refund`});await imsExecute(`UPDATE ims_supplier_credit_settlements SET status='succeeded',xero_id=?,completed_at=NOW() WHERE business_id=? AND action_key=?`,[paymentId,businessId,`${operationKey}:supplier_refund`]);}else if(settlement==='leave_unapplied'){await imsExecute(`UPDATE ims_supplier_credit_settlements SET status='succeeded',xero_id=?,completed_at=NOW() WHERE business_id=? AND action_key=?`,[xeroCreditNoteId,businessId,`${operationKey}:leave_unapplied`]);}await imsExecute(`UPDATE ims_po_shortfall_resolutions SET state='complete',completed_at=NOW() WHERE id=?`,[result.resolutionId]);result.xeroCreditNoteId=xeroCreditNoteId;result.state='complete';}else{await imsExecute(`UPDATE ims_po_shortfall_resolutions SET state='complete',completed_at=NOW() WHERE id=?`,[result.resolutionId]);result.state='complete';}return NextResponse.json({success:true,data:result});}catch(error:any){const message=String(error?.message??'Supplier outstanding quantity resolution failed.');const status=message.includes('already used')||message.includes('no longer')||message.includes('no outstanding')?409:message.includes('required')||message.includes('must be')||message.includes('Only ')?400:message.includes('not found')?404:500;if(status===500)await reportRuntimeIssue({businessId,source:'ims_purchase_orders',operation:'resolve_outstanding',title:'Supplier outstanding quantity resolution failed',error,reference:{type:'purchase_order',id:String(poId)}});return NextResponse.json({error:message},{status});}}
